/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace dsn.app.search
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class AugmentedQuery : TBase
  {
    private int _QueryId;
    private StringQuery _RawQuery;
    private StringQuery _AlteredQuery;
    private int _TopX;

    public int QueryId
    {
      get
      {
        return _QueryId;
      }
      set
      {
        __isset.QueryId = true;
        this._QueryId = value;
      }
    }

    public StringQuery RawQuery
    {
      get
      {
        return _RawQuery;
      }
      set
      {
        __isset.RawQuery = true;
        this._RawQuery = value;
      }
    }

    public StringQuery AlteredQuery
    {
      get
      {
        return _AlteredQuery;
      }
      set
      {
        __isset.AlteredQuery = true;
        this._AlteredQuery = value;
      }
    }

    public int TopX
    {
      get
      {
        return _TopX;
      }
      set
      {
        __isset.TopX = true;
        this._TopX = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool QueryId;
      public bool RawQuery;
      public bool AlteredQuery;
      public bool TopX;
    }

    public AugmentedQuery() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I32) {
              QueryId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.Struct) {
              RawQuery = new StringQuery();
              RawQuery.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 3:
            if (field.Type == TType.Struct) {
              AlteredQuery = new StringQuery();
              AlteredQuery.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 4:
            if (field.Type == TType.I32) {
              TopX = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("AugmentedQuery");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.QueryId) {
        field.Name = "QueryId";
        field.Type = TType.I32;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(QueryId);
        oprot.WriteFieldEnd();
      }
      if (RawQuery != null && __isset.RawQuery) {
        field.Name = "RawQuery";
        field.Type = TType.Struct;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        RawQuery.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (AlteredQuery != null && __isset.AlteredQuery) {
        field.Name = "AlteredQuery";
        field.Type = TType.Struct;
        field.ID = 3;
        oprot.WriteFieldBegin(field);
        AlteredQuery.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (__isset.TopX) {
        field.Name = "TopX";
        field.Type = TType.I32;
        field.ID = 4;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(TopX);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("AugmentedQuery(");
      bool __first = true;
      if (__isset.QueryId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("QueryId: ");
        __sb.Append(QueryId);
      }
      if (RawQuery != null && __isset.RawQuery) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("RawQuery: ");
        __sb.Append(RawQuery== null ? "<null>" : RawQuery.ToString());
      }
      if (AlteredQuery != null && __isset.AlteredQuery) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("AlteredQuery: ");
        __sb.Append(AlteredQuery== null ? "<null>" : AlteredQuery.ToString());
      }
      if (__isset.TopX) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("TopX: ");
        __sb.Append(TopX);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
