/**
 * Autogenerated by Thrift Compiler (@PACKAGE_VERSION@)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace dsn.app.search
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class PerDocStaticRank : TBase
  {
    private DocPosition _Pos;
    private int _StaticRank;

    public DocPosition Pos
    {
      get
      {
        return _Pos;
      }
      set
      {
        __isset.Pos = true;
        this._Pos = value;
      }
    }

    public int StaticRank
    {
      get
      {
        return _StaticRank;
      }
      set
      {
        __isset.StaticRank = true;
        this._StaticRank = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Pos;
      public bool StaticRank;
    }

    public PerDocStaticRank() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Struct) {
              Pos = new DocPosition();
              Pos.Read(iprot);
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I32) {
              StaticRank = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("PerDocStaticRank");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (Pos != null && __isset.Pos) {
        field.Name = "Pos";
        field.Type = TType.Struct;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        Pos.Write(oprot);
        oprot.WriteFieldEnd();
      }
      if (__isset.StaticRank) {
        field.Name = "StaticRank";
        field.Type = TType.I32;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(StaticRank);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("PerDocStaticRank(");
      bool __first = true;
      if (Pos != null && __isset.Pos) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Pos: ");
        __sb.Append(Pos== null ? "<null>" : Pos.ToString());
      }
      if (__isset.StaticRank) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("StaticRank: ");
        __sb.Append(StaticRank);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
